################################################################################
#  gpg-agent.conf -- my personal GnuPG agent configuration for Arch Linux PM
#                    see https://codeberg.org/hcartiaux/dotfiles
#
#  Copyright (c) 2026 Hyacinthe Cartiaux <hyacinthe.cartiaux@uni.lu>
#
################################################################################

# PIN entry program

pinentry-program /usr/bin/pinentry-qt

# Cache settings

default-cache-ttl 0
max-cache-ttl 0

# Socket path

extra-socket S.gpg-agent-archlinux.extra
